# Generated by Django 2.0.4 on 2018-04-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
